
--MERGE generated by 'sp_generate_merge' stored procedure, Version 0.93
--Originally by Vyas (http://vyaskn.tripod.com): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008/2012 by Daniel Nolan (http://danere.com)

SET NOCOUNT ON
GO

SET IDENTITY_INSERT [Group] ON
GO

MERGE INTO [Group] AS Target
USING (VALUES
  (1,N'Brick')
 ,(2,N'Plate')
 ,(3,N'Tile')
 ,(4,N'Bar')
 ,(5,N'Clip')
 ,(6,N'Curved')
 ,(7,N'Flag')
 ,(8,N'Handle')
 ,(9,N'Hinge')
 ,(10,N'Nature')
 ,(11,N'Other')
 ,(12,N'Round')
 ,(13,N'Slope')
 ,(14,N'Snot')
 ,(15,N'Socket')
 ,(16,N'Technic')
 ,(17,N'Wehicle')
 ,(18,N'Wall')
 ,(19,N'Wedge')
 ,(20,N'Minifig')
) AS Source ([Id],[Name])
ON (Target.[Id] = Source.[Id])
WHEN MATCHED AND (
	NULLIF(Source.[Name], Target.[Name]) IS NOT NULL OR NULLIF(Target.[Name], Source.[Name]) IS NOT NULL) THEN
 UPDATE SET
  [Name] = Source.[Name]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([Id],[Name])
 VALUES(Source.[Id],Source.[Name])
WHEN NOT MATCHED BY SOURCE THEN 
 DELETE
;
GO
DECLARE @mergeError int
 , @mergeCount int
SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [Group]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[Group] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
 END
GO

SET IDENTITY_INSERT [Group] OFF
GO
SET NOCOUNT OFF
GO
